<a href="https://colab.research.google.com/github/Twixx10/MachineLearningTASK/blob/main/Week1/02_Multiple_Linear_Regression_M%20Rakan%20Bagus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multiple Linear Regression

## Importing the libraries

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer


## Importing the dataset

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# Path ke file CSV
file_path = '/content/drive/MyDrive/Machine Learning/Dataset/50_Startups.csv'

# Membaca file CSV
dataset = pd.read_csv(file_path)

# Melihat 5 baris pertama dari dataset untuk memastikan datanya sudah benar
print(dataset.head())

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94


## Feature Engineering

In [ ]:
# Memisahkan fitur dan variabel target
X = dataset.iloc[:, :-1].values  # Semua kolom kecuali kolom terakhir (Profit)
y = dataset.iloc[:, -1].values   # Kolom terakhir (Profit)



In [ ]:
# Mengonversi variabel kategorikal 'State' menjadi dummy variables
# Kolom 'State' ada pada indeks ke-3 (index 3)
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

print(X[:5])  # Melihat beberapa data setelah encoding

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]]


## Splitting the dataset into the Training set and Test set

In [ ]:
# Membagi dataset menjadi Training set dan Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Melihat ukuran dataset yang telah dibagi
print(f"Ukuran X_train: {X_train.shape}, X_test: {X_test.shape}")

Ukuran X_train: (40, 6), X_test: (10, 6)


## Training the Multiple Linear Regression model on the Training set

In [ ]:
# Membuat dan melatih model Regresi Linear
regressor = LinearRegression()
regressor.fit(X_train, y_train)

print("Model telah dilatih dengan dataset Training.")

Model telah dilatih dengan dataset Training.


## Predicting the Test set results

In [ ]:
# Memprediksi hasil Test set
y_pred = regressor.predict(X_test)

# Menampilkan hasil prediksi vs nilai aktual
print("Hasil prediksi vs nilai aktual:")
comparison = pd.DataFrame({'Predicted': y_pred, 'Actual': y_test})
print(comparison)

Hasil prediksi vs nilai aktual:
       Predicted     Actual
0  103015.201598  103282.38
1  132582.277608  144259.40
2  132447.738452  146121.95
3   71976.098513   77798.83
4  178537.482211  191050.39
5  116161.242302  105008.31
6   67851.692097   81229.06
7   98791.733747   97483.56
8  113969.435330  110352.25
9  167921.065696  166187.94


#KESIMPULAN

## Kesimpulannya yaitu prediksi dari Test set menunjukkan bahwa model regresi linear yang kita buat mampu memperkirakan nilai keuntungan perusahaan startup dengan cukup baik, meskipun terdapat beberapa perbedaan antara nilai prediksi dan nilai aktual. Perbedaan ini bisa disebabkan oleh berbagai faktor, seperti data yang tidak mencakup semua variabel yang mempengaruhi keuntungan, atau variasi acak yang tidak dapat diprediksi. Namun secara umum, model memberikan gambaran yang cukup akurat mengenai faktor-faktor yang berpengaruh terhadap profit perusahaan.